name: Variables Example

on:
  workflow_dispatch:  # Only run this workflow manually

env:
  OVERWRITTEN_VAR: 'workflow value'
  UNDEFINED_VAR_WITH_DEFAULT: ${{ vars.UNDEFINED_VAR || 'default value' }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print Repository Variable
        run: echo "Repository variable:${{ env.REPOSITORY_VAR }}"  # Use env here

      - name: Print Workflow-Level Variables
        run: |
          echo "OVERWRITTEN_VAR: ${{ env.OVERWRITTEN_VAR }}"
          echo "UNDEFINED_VAR_WITH_DEFAULT: ${{ env.UNDEFINED_VAR_WITH_DEFAULT }}"

  echo2:
    runs-on: ubuntu-latest
    steps:
      - name: Print Variables
        run: |
          echo "Repo var: ${{ env.REPOSITORY_VAR }}"  # Use env here
          echo "Workflow overwritten var: ${{ env.OVERWRITTEN_VAR }}"

  echo-prod:
    runs-on: ubuntu-latest
    environment: prod  # Set the environment to prod
    steps:
      - name: Print Prod Variables
        run: |
          echo "Repo var: ${{ env.REPOSITORY_VAR }}"  # Use env here
          echo "Overwritten var: ${{ env.OVERWRITTEN_VAR }}"
          echo "Environment var: ${{ env.TARGET_VAR }}"

  echo-undefined:
    runs-on: ubuntu-latest
    steps:
      - name: Print Undefined Variables
        run: |
          echo "Undefined var with default: ${{ env.UNDEFINED_VAR_WITH_DEFAULT }}"
