name: 10- Working with Matrices

on:
  workflow_dispatch

jobs:
  backwards-compatibility:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x, 20.x, 21.x]
        os:
          - ubuntu-latest
          - windows-latest
      
        include:
         - os: ubuntu-latest
           node-version:  16.x
           tag: experimental

    name: ${{ matrix.os }}-Node${{ matrix.node-version }}

    steps:
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Fail if experimental
        if: matrix.tag == 'experimental'
        run: exit 1  # Fail if experimental tag is present

      - name: perform some tests
        run: |
         echo "Running tests on OS ${{ matrix.os }} and NodeJS ${{ matrix.node-version }}"

      - name: upload test results
        run: |
         echo "Uploading test results"
