name: 11 - 2 - Reusable Workflows

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/11-1-reusable-workflows.yml
    with:
      target-directory: "src"

  print-outputs:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
    - name: Print outputs
      run: |
        echo "Build status: ${{ needs.deploy.outputs.build-status }}"
        echo "URL: ${{ needs.deploy.outputs.url }}"
