name: CICD Example

# Triggers the workflow on push to the master branch or manual dispatch
on:
  push:
    branches:
      - feature1
  workflow_dispatch:

jobs:
  build:
    # Build Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Use a stable Node.js version compatible with `api-catalog-cli`

      - name: Install api-catalog cli
        run: |
          sudo apt-get update
          npm install -g api-catalog-cli@latest

      - name: Publish API to Anypoint Exchange
        env: 
          ANYPOINT_USERNAME: ${{ secrets.ANYPOINT_USERNAME }} 
          ANYPOINT_PASSWORD: ${{ secrets.ANYPOINT_PASSWORD }}
          ANYPOINT_ORG_ID: ${{ secrets.ANYPOINT_ORGID }}
        run: |
          api-catalog publish-asset --organization="$ANYPOINT_ORG_ID" --username="$ANYPOINT_USERNAME" --password="$ANYPOINT_PASSWORD"
